# Generated by Django 5.0 on 2025-03-06 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_title', models.CharField(max_length=255)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=255, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('academic_rank', models.CharField(max_length=50)),
                ('office_location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('courses_taught', models.ManyToManyField(related_name='lecturers', to='App.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('matric_number', models.CharField(max_length=255)),
                ('year_of_study', models.IntegerField()),
                ('courses_enrolled', models.ManyToManyField(related_name='students', to='App.course')),
                ('stundet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
