# Generated by Django 5.0 on 2025-03-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='stundet_name',
            new_name='student_name',
        ),
    ]
