# Generated by Django 5.0 on 2025-03-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_studentprofile_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='faculty',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
