# Generated by Django 5.0 on 2025-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_studentprofile_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
