# Generated by Django 5.0 on 2025-03-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_studentprofile_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='matric_number',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
