# Generated by Django 5.0 on 2026-07-26 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_attendancesession_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_time', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance', models.FloatField(help_text='Distance in meters from center')),
                ('status', models.CharField(default='Present', max_length=20)),
                ('face_similarity', models.FloatField(blank=True, help_text='Cosine similarity distance', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='radius',
            field=models.IntegerField(default=100, help_text='Geofence radius in meters'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['start_time'], name='App_attenda_start_t_4d7cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['course', 'lecturer'], name='App_attenda_course__1a8944_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_code'], name='App_course_course__2edff0_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_title'], name='App_course_course__9264da_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturerprofile',
            index=models.Index(fields=['staff_id'], name='App_lecture_staff_i_6a9094_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturerprofile',
            index=models.Index(fields=['department'], name='App_lecture_departm_137c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['matric_number'], name='App_student_matric__7acfce_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['department'], name='App_student_departm_f08287_idx'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='App.attendancesession'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'student'], name='App_attenda_session_e645c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'student')},
        ),
    ]
