# Generated by Django 5.0 on 2026-08-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_assessment_assessmentattempt_assessmentquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='academic_rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='office_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
