# Generated by Django 5.0 on 2026-08-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_assessmentattempt_anticheat_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('slides', 'Slides'), ('notes', 'Notes'), ('past_questions', 'Past Questions')], default='notes', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                ('content', models.TextField(blank=True, help_text='Extracted text content for AI processing')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='assessmentattempt',
            new_name='App_assessm_flagged_e02dc4_idx',
            old_name='app_assessm_flagged_idx',
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='App.course'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.lecturerprofile'),
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['course', 'material_type'], name='App_coursem_course__3c46a1_idx'),
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['uploaded_at'], name='App_coursem_uploade_b1fb18_idx'),
        ),
    ]
