# Generated by Django 5.0 on 2026-08-15 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_coursematerial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=20, null=True)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('domain', models.CharField(blank=True, max_length=50, null=True)),
                ('learning_style', models.CharField(blank=True, max_length=50, null=True)),
                ('bloom_level', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='App_aichatm_user_id_02e7b9_idx'), models.Index(fields=['course_code'], name='App_aichatm_course__0141b2_idx')],
            },
        ),
    ]
